name: build-focal

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: |
          ./bootstrap.sh 1
#      - name: Archive artifacts
 #       uses: actions/upload-artifact@v3
  #      with:
   #       name: ubuntu-from-scratch
    #      path: |
     #       scripts/ubuntu-from-scratch.iso
      #      scripts/image/md5sum.txt
